### ISSUE TITLE
Remove nomenclature.yaml

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/legacy-definitions#3]
As mentioned in the final comment of #2, we should remove `nomenclature.yaml` from this repo.
My reasoning is that, for the future I would imagine that a lot of projects would use a `nomenclature.yaml` like so:

```yaml
repositories:
  common-definitions:
    url: https://github.com/IAMconsortium/common-definitions.git/
  legacy-definitions:
    url: https://github.com/IAMconsortium/legacy-definitions.git/
definitions:
  variable:
    repository: 
      - common-definitions
      - legacy-definitions
```

This would, as it stands fail since legacy-definitions currently **contains** common-definitions so the above setup would double common-definitions leading to artificial duplicate code entries.
Therefore my suggestion would be to remove `nomenclature.yaml`.
The downside to that is that we would loose our pseudo integration test which currently runs on this repo and imports common-definitions to see if they are compatible with legacy-definitions. 
However, it might be better anyway to create a new repo in IAMconsortium just for this integration test purpose. This repo would contain no definitions of its own but rather just pull from both common as well as legacy definitions. I would then implement a trigger so that this runs on any change to either common or legacy definitions.

What are your thoughts @danielhuppmann?
